#!/bin/bash 

echo "deb http://download.proxmox.com/debian jessie pve-no-subscription" >> /etc/apt/sources.list
wget -O- "http://download.proxmox.com/debian/key.asc" | apt-key add -
apt-get update && apt-get dist-upgrade -y && reboot
dpkg-reconfigure locales
apt-get install proxmox-ve ntp ssh postfix ksm-control-daemon open-iscsi systemd-sysv

zabbix_agent_conf=/etc/zabbix/zabbix_agentd.conf
rules=/etc/iptables/rules.v4

# Add aliases
echo "alias reload_iptables='cat $rules | sudo iptables-restore -c'" >> /home/smaslov/.bashrc
echo "alias reload_iptables='cat $rules | sudo iptables-restore -c'" >> /root/.bashrc

# Remove pve enterprise repo
sed -i -e 's/deb/#deb/g' /etc/apt/sources.list.d/pve-enterprise.list
sed -i.bak "s/data.status !== 'Active'/false/g" /usr/share/pve-manager/ext6/pvemanagerlib.js

# Configure firewall
iptables -F
iptables -A INPUT -i lo -j ACCEPT
iptables -N zabbix
iptables -A INPUT -s 172.44.50.3/32 -j zabbix
iptables -A zabbix -p tcp --dport 10050 -j ACCEPT
iptables -A INPUT -p icmp -j ACCEPT
iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp -m multiport -s 172.44.50.1/28 --dports 22,8006 -j ACCEPT
iptables -A INPUT -p tcp -m multiport -s 192.168.49.1/24 --dports 111,3128,22,85,8006 -j ACCEPT
iptables -A INPUT -p udp -m multiport -s 192.168.49.1/24 --dports 5404,5405 -j ACCEPT
iptables -A INPUT -j DROP

# Install packages
apt-get update
apt-get install tcpdump vim iptables-persistent htop iftop iotop ethtool lm-sensors tmux curl zabbix-agent sudo mc fail2ban

# Edit firewall rules
service fail2ban stop
sed -i '/fail2ban/d' $rules
cat $rules | iptables-restore -c
service fail2ban start

# Edit Zabbix agent configuration
sed -i -e 's/Server=127.0.0.1/Server=172.44.50.3/g' $zabbix_agent_conf
sed -i -e 's/ServerActive=127.0.0.1/ServerActive=172.44.50.3/g' $zabbix_agent_conf
cat <<EOF >> $zabbix_agent_conf
EnableRemoteCommands=1
UserParameter=custom.softraid.status,egrep -c "\[.*_.*\]" /proc/mdstat
UserParameter=cpu_sensor,sensors | grep Physical | cut -b18-21
EOF

# Edit hosts
cat <<EOF > /etc/hosts
127.0.0.1	localhost
192.168.49.7	node04.asa.local	node04
192.168.49.3	node01.asa.local	node01
192.168.49.4	node02.asa.local	node02
192.168.49.6	node03.asa.local	node03
192.168.49.8	node05.asa.local	node05
192.168.49.10	gluster02.asa.local	gluster02
192.168.49.9	gluster01.asa.local 	gluster01

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

# Edit ethernet
cat <<EOF > /etc/network/interfaces
# network interface settings; autogenerated
# Please do NOT modify this file directly, unless you know what
# you're doing.
#
# If you want to manage part of the network configuration manually,
# please utilize the 'source' or 'source-directory' directives to do
# so.
# PVE will preserve these directives, but will NOT its network
# configuration from sourced files, so do not attempt to move any of
# the PVE managed interfaces into external files!

source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback
	allow hot-plug eth0

iface eth0 inet manual

iface eth1 inet manual

auto bond0
iface bond0 inet manual
	slaves eth0 eth1
	bond_miimon 100
	bond_mode balance-tlb

auto bond0.30
iface bond0.30 inet manual
	vlan-raw-device bond0

auto bond0.40
iface bond0.40 inet manual
	vlan-raw-device bond0

auto bond0.47
iface bond0.47 inet manual
	vlan-raw-device bond0

auto bond0.48
iface bond0.48 inet manual
	vlan-raw-device bond0

auto bond0.49
iface bond0.49 inet manual
	vlan-raw-device bond0

auto bond0.77
iface bond0.77 inet manual
	vlan-raw-device bond0

auto bond0.97
iface bond0.97 inet manual
	vlan-raw-device bond0

auto bond0.109
iface bond0.109 inet manual
	vlan-raw-device bond0

auto vmbr30
iface vmbr30 inet manual
	bridge_ports bond0.30
	bridge_stp off
	bridge_fd 0

auto vmbr40
iface vmbr40 inet manual
	bridge_ports bond0.40
	bridge_stp off
	bridge_fd 0

auto vmbr47
iface vmbr47 inet manual
	bridge_ports bond0.47
	bridge_stp off
	bridge_fd 0

auto vmbr48
iface vmbr48 inet manual
	bridge_ports bond0.48 bond0.48
	bridge_stp off
	bridge_fd 0

iface vmbr48 inet manual

auto vmbr49
iface vmbr49 inet dhcp
	bridge_ports bond0.49
	bridge_stp off
	bridge_fd 0

auto vmbr77
iface vmbr77 inet manual
	bridge_ports bond0.77
	bridge_stp off
	bridge_fd 0

auto vmbr97
iface vmbr97 inet manual
	bridge_ports bond0.97
	bridge_stp off
	bridge_fd 0

auto vmbr109
iface vmbr109 inet manual
	bridge_ports bond0.109
	bridge_stp off
	bridge_fd 0
EOF
